### PR TITLE
Add vfs support to runtime.

### PR DESCRIPTION
**Pull request by Berrysoft**
- [x] Runtime support
- [x] Plugin support
- [x] Frontend support
- [x] Custom `PackFS` based on ~~tar~~ [FRFS](https://github.com/Tim-Paik/frfs).

### CODE REVIEW

**Comment by Berrysoft** [comment]
Track: https://github.com/Tim-Paik/FRFS/pull/5

**Comment by Tim-Paik** [comment]
In addition, the documentation has to be changed

```
cargo doc
 Documenting frfs v0.2.0 (/home/timpaikx/Documents/frfs)
warning: unresolved link to `load_from_embed_file`
  --> src/lib.rs:17:6
   |
17 | //! [load_from_embed_file]: Load a FRFS file from frfs::File.
   |      ^^^^^^^^^^^^^^^^^^^^ no item named `load_from_embed_file` in scope
   |
   = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: `frfs` (lib doc) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.43s
```

**Comment by Berrysoft** [comment]
Track: https://github.com/Tim-Paik/FRFS/pull/8

**Comment by Akarinnnnn** [comment]
要不先拿zip过渡一下

**Comment by Berrysoft** [comment]
> 要不先拿zip过渡一下

这……都合并了，已经在用 FRFS 了。

zip 的问题是不支持 UTF8

**Pull request merged**
